//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_project_10514575_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class laptopdbEntities : DbContext
    {
        public laptopdbEntities()
            : base("name=laptopdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Branch> tbl_Branch { get; set; }
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_Client> tbl_Client { get; set; }
        public virtual DbSet<tbl_Laptop> tbl_Laptop { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<tbl_ServiceLine> tbl_ServiceLine { get; set; }
        public virtual DbSet<tbl_Services> tbl_Services { get; set; }
        public virtual DbSet<Service_Price> Service_Price { get; set; }
        public virtual DbSet<tablesview> tablesviews { get; set; }
    
        public virtual ObjectResult<GetLaptopServiceDetails_Result> GetLaptopServiceDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLaptopServiceDetails_Result>("GetLaptopServiceDetails");
        }
    
        public virtual ObjectResult<GroupbyHaving_Result> GroupbyHaving()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GroupbyHaving_Result>("GroupbyHaving");
        }
    
        public virtual int LaptopService(string clientEmail_Address)
        {
            var clientEmail_AddressParameter = clientEmail_Address != null ?
                new ObjectParameter("ClientEmail_Address", clientEmail_Address) :
                new ObjectParameter("ClientEmail_Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LaptopService", clientEmail_AddressParameter);
        }
    
        public virtual ObjectResult<RetrieveAllDetails_Result> RetrieveAllDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveAllDetails_Result>("RetrieveAllDetails");
        }
    
        public virtual ObjectResult<SelectPremiumUsers_Result> SelectPremiumUsers(string categoryType)
        {
            var categoryTypeParameter = categoryType != null ?
                new ObjectParameter("CategoryType", categoryType) :
                new ObjectParameter("CategoryType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPremiumUsers_Result>("SelectPremiumUsers", categoryTypeParameter);
        }
    }
}
