//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_project_10514575_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Services()
        {
            this.tbl_ServiceLine = new HashSet<tbl_ServiceLine>();
        }
    
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public float ServiceRate { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual tbl_Branch tbl_Branch { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ServiceLine> tbl_ServiceLine { get; set; }
    }
}
