//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_project_10514575_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceLine
    {
        public int ServiceNumber { get; set; }
        public int Quantity { get; set; }
        public float TotalServicePrice { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> SerialNo { get; set; }
    
        public virtual tbl_Laptop tbl_Laptop { get; set; }
        public virtual tbl_Order tbl_Order { get; set; }
        public virtual tbl_Services tbl_Services { get; set; }
    }
}
